// Seed data: sports venues/clubs and demo top players so the app is alive on first run
export const VENUES = [
  {
    id: 1,
    name: 'Nehru Stadium Sports Complex',
    type: 'Multi-sport complex',
    sports: ['Cricket', 'Football', 'Badminton'],
    address: 'Anna Salai, Periamet',
    latitude: 13.0802,
    longitude: 80.2735,
    rating: 4.6,
    reviews: 812,
    phone: '+91 44 2538 1122',
    priceLevel: 2,
    openNow: true,
  },
  {
    id: 2,
    name: 'Chennai Football Academy Turf',
    type: 'Football turf',
    sports: ['Football'],
    address: 'OMR, Perungudi',
    latitude: 12.9698,
    longitude: 80.2421,
    rating: 4.4,
    reviews: 356,
    phone: '+91 98410 22334',
    priceLevel: 2,
    openNow: true,
  },
  {
    id: 3,
    name: ' Marina Beach Cricket Ground',
    type: 'Open ground',
    sports: ['Cricket'],
    address: 'Marina Beach Road',
    latitude: 13.0500,
    longitude: 80.2824,
    rating: 4.1,
    reviews: 940,
    phone: null,
    priceLevel: 1,
    openNow: true,
  },
  {
    id: 4,
    name: 'Smash Point Badminton Courts',
    type: 'Indoor badminton',
    sports: ['Badminton'],
    address: 'Adyar, Lattice Bridge Road',
    latitude: 13.0012,
    longitude: 80.2565,
    rating: 4.5,
    reviews: 218,
    phone: '+91 99620 44556',
    priceLevel: 3,
    openNow: false,
  },
  {
    id: 5,
    name: 'Hoop District Basketball Arena',
    type: 'Basketball arena',
    sports: ['Basketball'],
    address: 'Nungambakkam High Road',
    latitude: 13.0569,
    longitude: 80.2425,
    rating: 4.3,
    reviews: 147,
    phone: '+91 90030 66778',
    priceLevel: 2,
    openNow: true,
  },
  {
    id: 6,
    name: 'Ace Tennis Academy',
    type: 'Tennis club',
    sports: ['Tennis'],
    address: 'Nungambakkam, Sterling Road',
    latitude: 13.0604,
    longitude: 80.2496,
    rating: 4.7,
    reviews: 265,
    phone: '+91 44 2817 3344',
    priceLevel: 3,
    openNow: true,
  },
  {
    id: 7,
    name: 'Velachery Sports Village',
    type: 'Multi-sport complex',
    sports: ['Cricket', 'Football', 'Basketball', 'Tennis'],
    address: 'Velachery Main Road',
    latitude: 12.9791,
    longitude: 80.2210,
    rating: 4.2,
    reviews: 389,
    phone: '+91 44 4301 5566',
    priceLevel: 2,
    openNow: true,
  },
  {
    id: 8,
    name: 'Guindy Turf Arena',
    type: 'Football + cricket turf',
    sports: ['Football', 'Cricket'],
    address: 'Guindy, Kathipara Junction',
    latitude: 12.9926,
    longitude: 80.2059,
    rating: 4.4,
    reviews: 173,
    phone: '+91 98847 88990',
    priceLevel: 2,
    openNow: true,
  },
];

// Demo "most popular players" — a real community will grow this via matches played.
// These users are flagged as demo: they are NOT real accounts and cannot be logged into.
export const DEMO_PLAYERS = [
  { uid: 9001, name: 'Arjun Kumar', sport: 'Football', skill: 'Advanced', rating: 4.9, matches: 134, bio: 'Striker. Sundays are sacred.', location: 'Adyar' },
  { uid: 9002, name: 'Priya Sharma', sport: 'Badminton', skill: 'Advanced', rating: 4.8, matches: 118, bio: 'Smash-first, questions later.', location: 'Velachery' },
  { uid: 9003, name: 'Rohit Verma', sport: 'Cricket', skill: 'Advanced', rating: 4.7, matches: 152, bio: 'Opening bat, off-spin when tired.', location: 'Guindy' },
  { uid: 9004, name: 'Sneha Iyer', sport: 'Tennis', skill: 'Intermediate', rating: 4.6, matches: 96, bio: 'Baseline grinder.', location: 'Nungambakkam' },
  { uid: 9005, name: 'Mohammed Ali', sport: 'Football', skill: 'Intermediate', rating: 4.5, matches: 88, bio: 'Wing play & overlap runs.', location: 'Triplicane' },
  { uid: 9006, name: 'Kavya Reddy', sport: 'Basketball', skill: 'Advanced', rating: 4.7, matches: 102, bio: 'Point guard. Talk defense!', location: 'Anna Nagar' },
  { uid: 9007, name: 'Vikram Singh', sport: 'Cricket', skill: 'Intermediate', rating: 4.4, matches: 77, bio: 'Pacer. Watch the yorker.', location: 'Perungudi' },
  { uid: 9008, name: 'Anjali Nair', sport: 'Badminton', skill: 'Intermediate', rating: 4.3, matches: 64, bio: 'Drop shots are my love language.', location: 'Adyar' },
];
